cabal-version:   3.4
name:            hqp
version:         0.1.0.0
synopsis:        HQP language playground in Haskell
license:         BSD-3-Clause
license-file:    LICENSE
author:          James Avery
maintainer:      avery@diku.dk
category:        Math
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall -Wno-orphans -Wno-unused-imports


common common-options
    default-language: GHC2021    
    default-extensions:
        NoMonomorphismRestriction,
        FlexibleContexts,
        FlexibleInstances,
        TypeFamilies,
        TypeSynonymInstances,
        BinaryLiterals,
        PatternSynonyms,
        ViewPatterns,
        LambdaCase,
        AllowAmbiguousTypes,
        TypeApplications,
        ScopedTypeVariables,
        GeneralizedNewtypeDeriving,
        DataKinds,
        UndecidableInstances,
        MagicHash

library core
    import:   warnings, common-options
    exposed-modules: 
      HQP
      HQP.QOp
      -- QOp syntax definitions and Operator typeclass:
      HQP.QOp.Syntax   
      -- QOp program transformations for optimization and analysis:
      HQP.QOp.Simplify 
      HQP.QOp.HelperFunctions
      -- HQP Semantics backend implementations:
      HQP.QOp.MatrixSemantics     
      HQP.QOp.StatevectorSemantics
      --HQP.QOp.StateHmatrixSemantics
      HQP.QOp.MPSSemantics
      HQP.QOp.StabilizerSemantics 
      -- Pretty-printing HQP programs and representations:
      HQP.PrettyPrint
      HQP.PrettyPrint.PrettyOp
      HQP.PrettyPrint.PrettyMatrix
      -- Example quantum programs written in HQP:
      Programs.QFT
      Programs.MatrixPreparation
      Programs.MatrixArithmetic
      Programs.Qubitization
      Programs.SVT
      Programs.QuantumAdder
      Programs.RepeaterProtocol

    build-depends:  
        base,
        hmatrix,
        random,
        mtl,
        array,
        containers,
        massiv,
        vector,
        integer-logarithms,
        deepseq,
        ieee754,
        pqueue,
        tasty,
        dsp
--        hasktorch
    hs-source-dirs:   src

common exe-common
  hs-source-dirs: exe
  build-depends:
      base,
      hmatrix,
      hqp:core
  ghc-options: -Wall

common test-common
  hs-source-dirs: test
  build-depends:
      base,
      hmatrix,
      hqp:core,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      QuickCheck
  ghc-options: -Wall

executable NoCloning
  import: exe-common
  main-is: NoCloning.hs


executable ProgramInversion
  import: exe-common
  main-is: ProgramInversion.hs
  ghc-options:
      -Wno-missing-signatures
      -Wno-name-shadowing
      -Wno-incomplete-uni-patterns

executable YesTeleportation
  import: exe-common
  build-depends:
    random
  main-is: YesTeleportation.hs

executable TestRepeater
  import: exe-common
  main-is: TestRepeater.hs
  build-depends:
    random
  ghc-options:
      -Wno-missing-signatures
      -Wno-name-shadowing
      -Wno-incomplete-uni-patterns

executable TestQFT
  import: exe-common
  main-is: TestQFT.hs
  build-depends:
    random
  ghc-options:
      -Wno-missing-signatures
      -Wno-name-shadowing
      -Wno-incomplete-uni-patterns      

executable MatrixPreparationTest
  import: exe-common
  build-depends:
    random,
    vector
  main-is: MatrixPreparationTest.hs
   
executable SVTtest
  import: exe-common
  build-depends:
    random,
    vector,
    dsp,
    containers
  main-is: SVTtest.hs

executable Qubitizationtest
  import: exe-common
  build-depends:
    random,
    vector,
    dsp
  main-is: Qubitizationtest.hs

executable BackendValidation
  import: test-common
  main-is: BackendValidation.hs
  other-modules: Generators

executable MatrixPrepTest
  import: test-common
  build-depends:
    vector
  main-is: MatrixPrepTest.hs

executable AlgebraTest
  import: test-common
  main-is: AlgebraTest.hs
  other-modules: Generators